[package]
name = "stark-felt"
version = "0.0.2"
edition = "2021"
license = "MIT"
homepage = "https://github.com/starknet-io/types-rs"
repository = "https://github.com/starknet-io/types-rs"
categories = ["types", "math", "crypto"]
keywords = ["stark", "zkp", "cairo"]
description = "Field element type for Cairo."
readme = "README.md"

[dependencies]
